DROP TABLE Cliente CASCADE CONSTRAINT;



create table Cliente(
CODIGO      NUMBER  CONSTRAINT PK_CLIENTE PRIMARY KEY,
NOME        VARCHAR2(60)       NOT NULL,
RUA         VARCHAR2(80)    NOT NULL,
NR          NUMBER(4)       NOT NULL,
BAIRRO      VARCHAR2(50)    NOT NULL,
COMPLEMENTO VARCHAR2(100)   NULL,
CIDADE      VARCHAR2(50)    NOT NULL,
UF          VARCHAR2(2)     NOT NULL,
CEP         VARCHAR2(10)    NOT NULL

);

DROP TABLE PF CASCADE CONSTRAINT;

CREATE TABLE PF (
CODIGO_CLI      NUMBER CONSTRAINT PK_CLIENTE_PF PRIMARY KEY,
CNPF            VARCHAR2(14)    NOT NULL,
RG              VARCHAR(10)     NOT NULL,
DATA_NASCIMENTO DATE            NOT NULL,
CONSTRAINT FK_PF_CLIENTE        FOREIGN KEY (CODIGO_CLI)    REFERENCES Cliente (CODIGO)
);

DROP TABLE PJ CASCADE CONSTRAINT;

CREATE TABLE PJ (
CODIGO_CLI      NUMBER CONSTRAINT PK_CLIENTE_PJ PRIMARY KEY,
CNPJ            VARCHAR2(19)        NOT NULL,
IE              VARCHAR2(10)        NOT NULL,
NOME_FANTASIA   VARCHAR2(60)        NOT NULL,
CONSTRAINT FK_PJ_CLIENTE        FOREIGN KEY (CODIGO_CLI)    REFERENCES Cliente (CODIGO)
);

DROP TABLE PRODUTO CASCADE CONSTRAINT;

CREATE TABLE PRODUTO (
CODIGO          NUMBER CONSTRAINT PK_PRODUTO PRIMARY KEY,
DESCRICAO       VARCHAR2(80)        NOT NULL,
UNID_MEDIDA     VARCHAR2(10)        NOT NULL
);

DROP TABLE VENDEDOR CASCADE CONSTRAINT;

CREATE TABLE VENDEDOR (
MATRICULA       NUMBER CONSTRAINT PK_VENDEDOR PRIMARY KEY,
NOME            VARCHAR2(60)        NOT NULL,
CNPF            VARCHAR2(14)        NOT NULL
);

DROP TABLE FONE_CLIENTE CASCADE CONSTRAINT;

CREATE TABLE FONE_CLIENTE (
NUMERO      VARCHAR2(14)    NOT NULL,
CODIGO_CLI  NUMBER      NOT NULL,
CONSTRAINT PK_FONE_CLIENTE PRIMARY KEY (NUMERO,CODIGO_CLI),
CONSTRAINT FK_FONE_CLIENTE_CLIENTE  FOREIGN KEY (CODIGO_CLI)    REFERENCES Cliente (CODIGO)
);


DROP TABLE FONE_VENDEDOR CASCADE CONSTRAINT;

CREATE TABLE FONE_VENDEDOR (
NUMERO      VARCHAR2(14)    NOT NULL,
CODIGO_CLI  NUMBER      NOT NULL,
CONSTRAINT PK_FONE_VENDEDOR PRIMARY KEY (NUMERO,CODIGO_CLI),
CONSTRAINT FK_FONE_VENDEDOR_VENDEDOR  FOREIGN KEY (CODIGO_CLI)    REFERENCES VENDEDOR (MATRICULA)
);

DROP TABLE PRATELEIRA CASCADE CONSTRAINT;

CREATE TABLE PRATELEIRA (
CODIGO          NUMBER(3) CONSTRAINT PK_ESTOQUE PRIMARY KEY,
DESCRICAO       VARCHAR2(50)       NOT NULL,
NUMERO_SECOES   NUMBER(2)          NOT NULL
);



DROP TABLE PEDIDO CASCADE CONSTRAINT;

CREATE TABLE PEDIDO (
NUMERO          NUMBER(6)       NOT NULL,
DATA            DATE            NOT NULL,
PRAZO_ENTREGA   DATE            NULL,
RUA             VARCHAR2(80)    NULL,
NR              NUMBER(4)       NULL,
BAIRRO          VARCHAR2(50)    NULL,
COMPLEMENTO     VARCHAR2(100)   NULL,
CIDADE          VARCHAR2(50)    NULL,
UF              VARCHAR2(2)     NULL,
CEP             VARCHAR2(10)    NULL,
TOTAL_FATURA    NUMBER(8,2)     NULL,
CODIGO_CLI      NUMBER          NOT NULL,
MATRICULA_VEN   NUMBER          NOT NULL
);

DROP TABLE ESTOQUE CASCADE CONSTRAINT;

CREATE TABLE ESTOQUE (
DATA_ENTRADA    DATE            NOT NULL,
CODIGO_PRO      NUMBER          NOT NULL,
CODIGO_PRA      NUMBER(3)       NOT NULL,
QUANTIDADE      NUMBER(5)       NOT NULL,
DATA_VALIDADE   DATE            NULL
);

DROP TABLE CAPACIDADE_ESTOQUE CASCADE CONSTRAINT;

CREATE TABLE CAPACIDADE_ESTOQUE (
CODIGO_PRO      NUMBER          NOT NULL,
CODIGO_PRA      NUMBER(3)       NOT NULL,
QUANTIDADE      NUMBER(5)       NOT NULL
);

DROP TABLE ITEM_PRODUTO CASCADE CONSTRAINT;

CREATE TABLE ITEM_PRODUTO (
CODIGO_PRO      NUMBER          NOT NULL,
NUMERO_PED      NUMBER(6)       NOT NULL,
QUANTIDADE      NUMBER(5)       NOT NULL,
PRECO_UNITARIO  NUMBER(5,2)     NOT NULL,
VALOR_ITEM      NUMBER(7,2)     NULL
);

ALTER TABLE PEDIDO
ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO);

ALTER TABLE ESTOQUE
ADD CONSTRAINT PK_ESTOQUE PRIMARY KEY (DATA_ENTRADA, CODIGO_PRO, CODIGO_PRA);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT PK_CAPACIDADE_ESTOQUE PRIMARY KEY (CODIGO_PRO, CODIGO_PRA);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY (CODIGO_PRO, NUMERO_PED);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_CLIENTE FOREIGN KEY (CODIGO_CLI)
REFERENCES CLIENTE (CODIGO);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_VENDEDOR FOREIGN KEY (MATRICULA_VEN)
REFERENCES VENDEDOR (MATRICULA);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_EST_PRODUTO FOREIGN KEY (CODIGO_PRO)
REFERENCES PRODUTO (CODIGO);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_EST_PRATELEIRA FOREIGN KEY (CODIGO_PRA)
REFERENCES PRATELEIRA (CODIGO);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAP_EST_PRODUTO FOREIGN KEY (CODIGO_PRO)
REFERENCES PRODUTO (CODIGO);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAP_EST_PRATELEIRA FOREIGN KEY (CODIGO_PRA)
REFERENCES PRATELEIRA (CODIGO);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (CODIGO_PRO)
REFERENCES PRODUTO (CODIGO);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (NUMERO_PED)
REFERENCES PEDIDO (NUMERO);


ALTER TABLE PEDIDO
ADD CONSTRAINT CK_NUMERO_PEDIDO CHECK (NUMERO BETWEEN 1 AND 99999);


CREATE UNIQUE INDEX IND_CNPF_PF ON PF (CNPF);

ALTER TABLE PF
ADD CONSTRAINT UK_PF_CNPF UNIQUE (CNPF)
USING INDEX IND_CNPF_PF;

CREATE UNIQUE INDEX IND_CNPJ_PJ ON PJ (CNPJ);

ALTER TABLE PJ
ADD CONSTRAINT UK_PJ_CNPJ UNIQUE (CNPJ)
USING INDEX IND_CNPJ_PJ;


DROP SEQUENCE SEQ_ITEM_ID;

CREATE SEQUENCE SEQ_ITEM_ID
START WITH 1
INCREMENT BY 2
NOCACHE
NOCYCLE;



COMMENT ON TABLE ITEM_PRODUTO IS
'Tabela associativa que registra os produtos de cada pedido, com quantidade, preco unitario e valor do item';

COMMENT ON COLUMN ITEM_PRODUTO.CODIGO_PRO IS
'Codigo do produto do item (PK e FK para PRODUTO)';

COMMENT ON COLUMN ITEM_PRODUTO.NUMERO_PED IS
'Numero do pedido ao qual o item pertence (PK e FK para PEDIDO)';

COMMENT ON COLUMN ITEM_PRODUTO.QUANTIDADE IS
'Quantidade do produto solicitada no pedido';

COMMENT ON COLUMN ITEM_PRODUTO.PRECO_UNITARIO IS
'Preco unitario do produto no momento do pedido';

COMMENT ON COLUMN ITEM_PRODUTO.VALOR_ITEM IS
'Valor total do item (QUANTIDADE x PRECO_UNITARIO)';

